# Generated by Django 5.2.7 on 2025-10-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SleepSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_min", models.IntegerField()),
                ("efficiency", models.FloatField()),
                ("latency", models.FloatField(help_text="Minutes to fall asleep")),
                ("rem_hours", models.FloatField()),
                ("deep_hours", models.FloatField()),
                ("hrv", models.FloatField(help_text="Heart rate variability")),
                ("rhr", models.FloatField(help_text="Resting heart rate")),
                ("score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
